version: "3"

services:
  app:
    container_name: desafio1
    build: .
    ports:
      - "50052:50051"
      - "8000:8000"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"